# PG-HA 专用配置;自兜底 DATA_ROOT,不加载主 lib/config.sh
DATA_ROOT="${DATA_ROOT:-/data}"

PG_HA_MAJOR_VERSION="${PG_HA_MAJOR_VERSION:-18}"
PG_HA_CLUSTER_NAME="${PG_HA_CLUSTER_NAME:-pg-ha}"

PG_HA_PG_PORT="${PG_HA_PG_PORT:-5432}"
PG_HA_PATRONI_REST_PORT="${PG_HA_PATRONI_REST_PORT:-8008}"
PG_HA_ETCD_CLIENT_PORT="${PG_HA_ETCD_CLIENT_PORT:-2379}"
PG_HA_ETCD_PEER_PORT="${PG_HA_ETCD_PEER_PORT:-2380}"
PG_HA_PROXY_PORT="${PG_HA_PROXY_PORT:-5000}"
PG_HA_PROXY_STATS_PORT="${PG_HA_PROXY_STATS_PORT:-7000}"

PG_HA_PGDATA="${PG_HA_PGDATA:-${DATA_ROOT}/patroni/pgdata}"
PG_HA_ETCD_DATA="${PG_HA_ETCD_DATA:-${DATA_ROOT}/etcd}"

PG_HA_TTL="${PG_HA_TTL:-30}"
PG_HA_LOOP_WAIT="${PG_HA_LOOP_WAIT:-10}"
PG_HA_RETRY_TIMEOUT="${PG_HA_RETRY_TIMEOUT:-10}"
PG_HA_MAX_LAG_ON_FAILOVER="${PG_HA_MAX_LAG_ON_FAILOVER:-1048576}"
PG_HA_MAX_SLOT_WAL_KEEP_SIZE="${PG_HA_MAX_SLOT_WAL_KEEP_SIZE:-10GB}"

PG_HA_SYNC_MODE="${PG_HA_SYNC_MODE:-off}"
PG_HA_SYNC_STRICT="${PG_HA_SYNC_STRICT:-off}"
PG_HA_SERVER_TYPE="${PG_HA_SERVER_TYPE:-auto}"
PG_HA_WATCHDOG="${PG_HA_WATCHDOG:-auto}"
PG_HA_WATCHDOG_DEVICE="${PG_HA_WATCHDOG_DEVICE:-/dev/watchdog}"

PG_HA_APP_ALLOWED_CIDR="${PG_HA_APP_ALLOWED_CIDR:-}"

PG_HA_SUPERUSER_PASSWORD="${PG_HA_SUPERUSER_PASSWORD:-}"
PG_HA_REPLICATION_PASSWORD="${PG_HA_REPLICATION_PASSWORD:-}"
PG_HA_REWIND_PASSWORD="${PG_HA_REWIND_PASSWORD:-}"
PG_HA_ETCD_PASSWORD="${PG_HA_ETCD_PASSWORD:-}"
PG_HA_REST_PASSWORD="${PG_HA_REST_PASSWORD:-}"
PG_HA_STATS_PASSWORD="${PG_HA_STATS_PASSWORD:-}"

PG_HA_NODE1_IP="${PG_HA_NODE1_IP:-}"
PG_HA_NODE2_IP="${PG_HA_NODE2_IP:-}"
PG_HA_NODE3_IP="${PG_HA_NODE3_IP:-}"

# 运行期由 collect_config 设定
PG_HA_ROLE="${PG_HA_ROLE:-}"
PG_HA_NODE_NAME="${PG_HA_NODE_NAME:-}"
PG_HA_NODE_IP="${PG_HA_NODE_IP:-}"

# 文件路径(测试 export 覆盖到临时目录)
PG_HA_ETCD_CONFIG_FILE="${PG_HA_ETCD_CONFIG_FILE:-/etc/etcd/etcd.conf.yml}"
PG_HA_ETCD_UNIT_DROPIN="${PG_HA_ETCD_UNIT_DROPIN:-/etc/systemd/system/etcd.service.d/override.conf}"
PG_HA_PATRONI_YAML="${PG_HA_PATRONI_YAML:-/etc/patroni/patroni.yml}"
PG_HA_PATRONI_UNIT="${PG_HA_PATRONI_UNIT:-/etc/systemd/system/patroni.service}"
PG_HA_HAPROXY_CFG="${PG_HA_HAPROXY_CFG:-/etc/haproxy/haproxy.cfg}"
