DATA_ROOT="${DATA_ROOT:-/data}"
DOCKER_DIR="${DOCKER_DIR:-${DATA_ROOT}/docker}"
CADDY_ETC_DIR="${CADDY_ETC_DIR:-/etc/caddy}"
CADDY_MAIN_FILE="${CADDY_MAIN_FILE:-${CADDY_ETC_DIR}/Caddyfile}"
CADDY_CONF_DIR="${CADDY_CONF_DIR:-${CADDY_ETC_DIR}/conf}"
ROOT_HOME="${ROOT_HOME:-/root}"

POSTGRES_DIR="${POSTGRES_DIR:-${DATA_ROOT}/postgres}"
MYSQL_DIR="${MYSQL_DIR:-${DATA_ROOT}/mysql}"
RABBITMQ_DIR="${RABBITMQ_DIR:-${DATA_ROOT}/rabbitmq}"
REDIS_DIR="${REDIS_DIR:-${DATA_ROOT}/redis}"

POSTGRES_COMPOSE_FILE="${POSTGRES_COMPOSE_FILE:-${DOCKER_DIR}/docker-postgres.yml}"
MYSQL_COMPOSE_FILE="${MYSQL_COMPOSE_FILE:-${DOCKER_DIR}/docker-mysql.yml}"
RABBITMQ_COMPOSE_FILE="${RABBITMQ_COMPOSE_FILE:-${DOCKER_DIR}/docker-rabbitmq.yml}"
REDIS_COMPOSE_FILE="${REDIS_COMPOSE_FILE:-${DOCKER_DIR}/docker-redis.yml}"
MYSQL_CONFIG_FILE="${MYSQL_CONFIG_FILE:-${MYSQL_DIR}/conf/my.cnf}"
MYSQL_INIT_DIR="${MYSQL_INIT_DIR:-${MYSQL_DIR}/init}"
MYSQL_INIT_FILE="${MYSQL_INIT_FILE:-${MYSQL_INIT_DIR}/01-app-user.sql}"
RABBITMQ_CONF_DIR="${RABBITMQ_CONF_DIR:-${RABBITMQ_DIR}/conf}"
RABBITMQ_CONFIG_FILE="${RABBITMQ_CONFIG_FILE:-${RABBITMQ_CONF_DIR}/rabbitmq.conf}"
RABBITMQ_ENABLED_PLUGINS_FILE="${RABBITMQ_ENABLED_PLUGINS_FILE:-${RABBITMQ_CONF_DIR}/enabled_plugins}"

POSTGRES_IMAGE="${POSTGRES_IMAGE:-postgres:18.3}"
MYSQL_IMAGE="${MYSQL_IMAGE:-mysql:8.4.8}"
RABBITMQ_IMAGE="${RABBITMQ_IMAGE:-rabbitmq:management}"
REDIS_IMAGE="${REDIS_IMAGE:-redis:8.6.1}"

DEFAULT_POSTGRES_PORT="${DEFAULT_POSTGRES_PORT:-5432}"
DEFAULT_POSTGRES_DB="${DEFAULT_POSTGRES_DB:-appdb}"
DEFAULT_POSTGRES_USER="${DEFAULT_POSTGRES_USER:-postgres}"
DEFAULT_POSTGRES_PASSWORD="${DEFAULT_POSTGRES_PASSWORD:-postgres123}"

DEFAULT_MYSQL_PORT="${DEFAULT_MYSQL_PORT:-3306}"
DEFAULT_MYSQL_DB="${DEFAULT_MYSQL_DB:-appdb}"
DEFAULT_MYSQL_USER="${DEFAULT_MYSQL_USER:-app}"
DEFAULT_MYSQL_PASSWORD="${DEFAULT_MYSQL_PASSWORD:-app123}"
DEFAULT_MYSQL_ROOT_PASSWORD="${DEFAULT_MYSQL_ROOT_PASSWORD:-root123}"

DEFAULT_RABBITMQ_PORT="${DEFAULT_RABBITMQ_PORT:-5672}"
DEFAULT_RABBITMQ_MANAGEMENT_PORT="${DEFAULT_RABBITMQ_MANAGEMENT_PORT:-15672}"
DEFAULT_RABBITMQ_WEB_STOMP_PORT="${DEFAULT_RABBITMQ_WEB_STOMP_PORT:-15674}"
DEFAULT_RABBITMQ_USER="${DEFAULT_RABBITMQ_USER:-admin}"
DEFAULT_RABBITMQ_PASSWORD="${DEFAULT_RABBITMQ_PASSWORD:-admin123}"

DEFAULT_REDIS_PORT="${DEFAULT_REDIS_PORT:-6379}"
DEFAULT_REDIS_PASSWORD="${DEFAULT_REDIS_PASSWORD:-}"

SELECT_CADDY=0
SELECT_POSTGRES=0
SELECT_MYSQL=0
SELECT_RABBITMQ=0
SELECT_REDIS=0
SELECT_PG_WRAPPER=0
SELECT_DOCKER=0

POSTGRES_PORT="$DEFAULT_POSTGRES_PORT"
POSTGRES_DB="$DEFAULT_POSTGRES_DB"
POSTGRES_USER="$DEFAULT_POSTGRES_USER"
POSTGRES_PASSWORD="$DEFAULT_POSTGRES_PASSWORD"

MYSQL_PORT="$DEFAULT_MYSQL_PORT"
MYSQL_DB="$DEFAULT_MYSQL_DB"
MYSQL_USER="$DEFAULT_MYSQL_USER"
MYSQL_PASSWORD="$DEFAULT_MYSQL_PASSWORD"
MYSQL_ROOT_PASSWORD="$DEFAULT_MYSQL_ROOT_PASSWORD"

RABBITMQ_PORT="$DEFAULT_RABBITMQ_PORT"
RABBITMQ_MANAGEMENT_PORT="$DEFAULT_RABBITMQ_MANAGEMENT_PORT"
RABBITMQ_WEB_STOMP_PORT="$DEFAULT_RABBITMQ_WEB_STOMP_PORT"
RABBITMQ_USER="$DEFAULT_RABBITMQ_USER"
RABBITMQ_PASSWORD="$DEFAULT_RABBITMQ_PASSWORD"

REDIS_PORT="$DEFAULT_REDIS_PORT"
REDIS_PASSWORD="$DEFAULT_REDIS_PASSWORD"

POSTGRES_PROJECT_NAME="${POSTGRES_PROJECT_NAME:-postgres}"
MYSQL_PROJECT_NAME="${MYSQL_PROJECT_NAME:-mysql}"
RABBITMQ_PROJECT_NAME="${RABBITMQ_PROJECT_NAME:-rabbitmq}"
REDIS_PROJECT_NAME="${REDIS_PROJECT_NAME:-redis}"
SHARED_NETWORK_NAME="${SHARED_NETWORK_NAME:-my_network}"
PG_WRAPPER_BIN="${PG_WRAPPER_BIN:-/usr/local/bin/pg}"
INSTALLED_PG_WRAPPER_USER=""
