#!/usr/bin/env bash
# lib/db-tenant/config.sh — 数据库多租户管理工具默认配置(可被环境变量覆盖)

DATA_ROOT="${DATA_ROOT:-/data}"

DB_TENANT_PG_CONTAINER="${DB_TENANT_PG_CONTAINER:-postgres}"
DB_TENANT_MYSQL_CONTAINER="${DB_TENANT_MYSQL_CONTAINER:-mysql}"
DB_TENANT_FORCE_TARGET="${DB_TENANT_FORCE_TARGET:-}"

DB_TENANT_MYSQL_ADMIN_USER="${DB_TENANT_MYSQL_ADMIN_USER:-root}"
DB_TENANT_MYSQL_ADMIN_PASSWORD="${DB_TENANT_MYSQL_ADMIN_PASSWORD:-}"
DB_TENANT_MYSQL_SOCKET="${DB_TENANT_MYSQL_SOCKET:-/var/run/mysqld/mysqld.sock}"

DB_TENANT_BACKUP_DIR="${DB_TENANT_BACKUP_DIR:-/var/backups/db-tenant}"
DB_TENANT_BACKUP_MIN_FREE_MB="${DB_TENANT_BACKUP_MIN_FREE_MB:-512}"

DB_TENANT_PG_CONN_LIMIT="${DB_TENANT_PG_CONN_LIMIT:-20}"
DB_TENANT_PG_DB_CONN_LIMIT="${DB_TENANT_PG_DB_CONN_LIMIT:-20}"
DB_TENANT_PG_STATEMENT_TIMEOUT="${DB_TENANT_PG_STATEMENT_TIMEOUT:-30s}"
DB_TENANT_PG_IDLE_TX_TIMEOUT="${DB_TENANT_PG_IDLE_TX_TIMEOUT:-300s}"
DB_TENANT_PG_WORK_MEM="${DB_TENANT_PG_WORK_MEM:-16MB}"

DB_TENANT_MYSQL_MAX_USER_CONN="${DB_TENANT_MYSQL_MAX_USER_CONN:-20}"
DB_TENANT_MYSQL_MAX_CONN_PER_HOUR="${DB_TENANT_MYSQL_MAX_CONN_PER_HOUR:-0}"
DB_TENANT_MYSQL_MAX_QUERIES_PER_HOUR="${DB_TENANT_MYSQL_MAX_QUERIES_PER_HOUR:-0}"
DB_TENANT_MYSQL_MAX_UPDATES_PER_HOUR="${DB_TENANT_MYSQL_MAX_UPDATES_PER_HOUR:-0}"
DB_TENANT_MYSQL_DEFAULT_HOST="${DB_TENANT_MYSQL_DEFAULT_HOST:-%}"

DB_TENANT_PG_SYSTEM_NAMES="${DB_TENANT_PG_SYSTEM_NAMES:-postgres template0 template1}"
DB_TENANT_MYSQL_SYSTEM_USERS="${DB_TENANT_MYSQL_SYSTEM_USERS:-root mysql.sys mysql.session mysql.infoschema sys debian-sys-maint repl mysqlchk repman}"
DB_TENANT_MYSQL_SYSTEM_DATABASES="${DB_TENANT_MYSQL_SYSTEM_DATABASES:-mysql information_schema performance_schema sys replication_manager_schema}"
