# MySQL-HA 专用配置;自兜底 DATA_ROOT,不加载主 lib/config.sh
DATA_ROOT="${DATA_ROOT:-/data}"

MYSQL_HA_VERSION="${MYSQL_HA_VERSION:-8.4}"
MYSQL_HA_CLUSTER_NAME="${MYSQL_HA_CLUSTER_NAME:-mysql-ha}"

MYSQL_HA_MYSQL_PORT="${MYSQL_HA_MYSQL_PORT:-3306}"
MYSQL_HA_PROXY_PORT="${MYSQL_HA_PROXY_PORT:-6446}"
MYSQL_HA_PROXY_STATS_PORT="${MYSQL_HA_PROXY_STATS_PORT:-7001}"
MYSQL_HA_MYSQLCHK_PORT="${MYSQL_HA_MYSQLCHK_PORT:-9200}"
MYSQL_HA_ORCH_PORT="${MYSQL_HA_ORCH_PORT:-3000}"
MYSQL_HA_ORCH_RAFT_PORT="${MYSQL_HA_ORCH_RAFT_PORT:-10008}"

MYSQL_HA_DATADIR="${MYSQL_HA_DATADIR:-${DATA_ROOT}/mysql-ha/data}"
MYSQL_HA_ORCH_DATADIR="${MYSQL_HA_ORCH_DATADIR:-${DATA_ROOT}/mysql-ha/orchestrator}"

MYSQL_HA_WATCHER_INTERVAL="${MYSQL_HA_WATCHER_INTERVAL:-5}"
MYSQL_HA_INSTANCE_POLL_SECONDS="${MYSQL_HA_INSTANCE_POLL_SECONDS:-5}"
MYSQL_HA_RECOVERY_BLOCK_SECONDS="${MYSQL_HA_RECOVERY_BLOCK_SECONDS:-3600}"
MYSQL_HA_PROMOTION_LAG_SECONDS="${MYSQL_HA_PROMOTION_LAG_SECONDS:-60}"
MYSQL_HA_BINLOG_EXPIRE_SECONDS="${MYSQL_HA_BINLOG_EXPIRE_SECONDS:-604800}"

MYSQL_HA_SEMISYNC="${MYSQL_HA_SEMISYNC:-off}"
MYSQL_HA_SEMISYNC_TIMEOUT="${MYSQL_HA_SEMISYNC_TIMEOUT:-1000}"

MYSQL_HA_APP_DB="${MYSQL_HA_APP_DB:-appdb}"
MYSQL_HA_APP_USER="${MYSQL_HA_APP_USER:-appuser}"
MYSQL_HA_APP_ALLOWED_CIDR="${MYSQL_HA_APP_ALLOWED_CIDR:-}"

MYSQL_HA_ROOT_PASSWORD="${MYSQL_HA_ROOT_PASSWORD:-}"
MYSQL_HA_REPL_PASSWORD="${MYSQL_HA_REPL_PASSWORD:-}"
MYSQL_HA_ORCH_PASSWORD="${MYSQL_HA_ORCH_PASSWORD:-}"
MYSQL_HA_ORCH_HTTP_PASSWORD="${MYSQL_HA_ORCH_HTTP_PASSWORD:-}"
MYSQL_HA_MYSQLCHK_PASSWORD="${MYSQL_HA_MYSQLCHK_PASSWORD:-}"
MYSQL_HA_WATCHER_PASSWORD="${MYSQL_HA_WATCHER_PASSWORD:-}"
MYSQL_HA_APP_PASSWORD="${MYSQL_HA_APP_PASSWORD:-}"
MYSQL_HA_STATS_PASSWORD="${MYSQL_HA_STATS_PASSWORD:-}"

MYSQL_HA_NODE1_IP="${MYSQL_HA_NODE1_IP:-}"
MYSQL_HA_NODE2_IP="${MYSQL_HA_NODE2_IP:-}"
MYSQL_HA_NODE3_IP="${MYSQL_HA_NODE3_IP:-}"

# 服务账号用户名(随 MySQL 运行用户;cnf 文件 owner 须 = 对应 service User)
MYSQL_HA_SERVICE_USER="${MYSQL_HA_SERVICE_USER:-mysql}"

# 运行期由 collect_config 设定
MYSQL_HA_ROLE="${MYSQL_HA_ROLE:-}"
MYSQL_HA_NODE_NAME="${MYSQL_HA_NODE_NAME:-}"
MYSQL_HA_NODE_IP="${MYSQL_HA_NODE_IP:-}"
MYSQL_HA_SERVER_ID="${MYSQL_HA_SERVER_ID:-}"

# 文件路径(测试 export 覆盖到临时目录)
MYSQL_HA_MYCNF="${MYSQL_HA_MYCNF:-/etc/mysql/mysql.conf.d/zz-mysql-ha.cnf}"
MYSQL_HA_ORCH_CONF="${MYSQL_HA_ORCH_CONF:-/etc/orchestrator.conf.json}"
MYSQL_HA_ORCH_UNIT="${MYSQL_HA_ORCH_UNIT:-/etc/systemd/system/orchestrator.service}"
MYSQL_HA_ORCH_CLIENT_CNF="${MYSQL_HA_ORCH_CLIENT_CNF:-/etc/mysql/orchestrator-client.cnf}"
MYSQL_HA_HAPROXY_CFG="${MYSQL_HA_HAPROXY_CFG:-/etc/haproxy/haproxy.cfg}"
MYSQL_HA_MYSQLCHK_SCRIPT="${MYSQL_HA_MYSQLCHK_SCRIPT:-/usr/local/bin/mysqlchk}"
MYSQL_HA_MYSQLCHK_SOCKET="${MYSQL_HA_MYSQLCHK_SOCKET:-/etc/systemd/system/mysqlchk.socket}"
MYSQL_HA_MYSQLCHK_SERVICE="${MYSQL_HA_MYSQLCHK_SERVICE:-/etc/systemd/system/mysqlchk@.service}"
MYSQL_HA_MYSQLCHK_CNF="${MYSQL_HA_MYSQLCHK_CNF:-/etc/mysql/mysqlchk.cnf}"
MYSQL_HA_WATCHER_SCRIPT="${MYSQL_HA_WATCHER_SCRIPT:-/usr/local/bin/mysql-ha-watcher}"
MYSQL_HA_WATCHER_UNIT="${MYSQL_HA_WATCHER_UNIT:-/etc/systemd/system/mysql-ha-watcher.service}"
MYSQL_HA_WATCHER_CNF="${MYSQL_HA_WATCHER_CNF:-/etc/mysql/mysql-ha-watcher.cnf}"
MYSQL_HA_MYSQL_SOCKET="${MYSQL_HA_MYSQL_SOCKET:-/var/run/mysqld/mysqld.sock}"
